# application-github.properties

# Deshabilitar la conexion a la base de datos en GitHub Actions
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Otros ajustes para el profile github
spring.jpa.hibernate.ddl-auto=none
